In [6]:
import pandas as pd

df =pd.read_json("sample_Data.json")
print("Reading the first 5 rows\n")
df.head(5)

Reading the first 5 rows

,id,name,description,price,category,image
0,1,Apple iPhone 12,The Apple iPhone 12 features a 6.1-inch Super ...,999.00,Electronics,https://www.apple.com/newsroom/images/product/...
1,2,Samsung Galaxy S21,The Samsung Galaxy S21 features a 6.2-inch Dyn...,799.00,Electronics,https://images.samsung.com/is/image/samsung/p6...
2,3,Sony PlayStation 5,The Sony PlayStation 5 features an AMD Zen 2-b...,499.99,Electronics,https://www.sony.com/image/44baa604124b770c824...
3,4,LG OLED55CXPUA 55-inch 4K OLED TV,The LG OLED55CXPUA 55-inch 4K OLED TV features...,1599.99,Electronics,https://www.lg.com/us/images/tvs/md07501804/ga...
4,5,Bose QuietComfort 35 II Wireless Headphones,The Bose QuietComfort 35 II Wireless Headphone...,299.00,Electronics,https://assets.bose.com/content/dam/Bose_DAM/W...

In [7]:
print("Reading the last 5 rows\n")
df.tail(5)

Reading the last 5 rows

,id,name,description,price,category,image
15,16,Breville Barista Express Espresso Machine,The Breville Barista Express Espresso Machine ...,699.95,Home & Kitchen,https://www.breville.com/content/dam/breville/...
16,17,Keurig K-Elite Coffee Maker,The Keurig K-Elite Coffee Maker features a str...,169.99,Home & Kitchen,https://www.keurig.com/content/dam/global-ecom...
17,18,iRobot Roomba i7+ Robot Vacuum,The iRobot Roomba i7+ Robot Vacuum features au...,799.99,Home & Kitchen,https://store.irobot.com/default/i7-vacuuming-...
18,19,Ninja Foodi Digital Air Fry Oven,The Ninja Foodi Digital Air Fry Oven features ...,209.99,Home & Kitchen,https://www.ninjakitchen.com/static/img/produc...
19,20,Cuisinart ICE-70 Ice Cream Maker,The Cuisinart ICE-70 Ice Cream Maker features ...,139.99,Home & Kitchen,https://www.cuisinart.com/share/images/product...